from . import (
    axis,
    bandhan,
    bob,
    canara,
    citibank,
    cityunion,
    dbs,
    dcb,
    hdfc,
    hsbc,
    icici,
    idbi,
    idfcfirst,
    jkbank,
    kotak,
    kvb,
    iob,
    sbi,
    ujjivan,
)

REGISTRY = {
    axis.PLUGIN.slug: axis.PLUGIN,
    iob.PLUGIN.slug: iob.PLUGIN,
    bob.PLUGIN.slug: bob.PLUGIN,
    canara.PLUGIN.slug: canara.PLUGIN,
    sbi.PLUGIN.slug: sbi.PLUGIN,
    hdfc.PLUGIN.slug: hdfc.PLUGIN,
    kotak.PLUGIN.slug: kotak.PLUGIN,
    idbi.PLUGIN.slug: idbi.PLUGIN,
    cityunion.PLUGIN.slug: cityunion.PLUGIN,
    hsbc.PLUGIN.slug: hsbc.PLUGIN,
    jkbank.PLUGIN.slug: jkbank.PLUGIN,
    kvb.PLUGIN.slug: kvb.PLUGIN,
    ujjivan.PLUGIN.slug: ujjivan.PLUGIN,
    idfcfirst.PLUGIN.slug: idfcfirst.PLUGIN,
    dbs.PLUGIN.slug: dbs.PLUGIN,
    citibank.PLUGIN.slug: citibank.PLUGIN,
    icici.PLUGIN.slug: icici.PLUGIN,
    bandhan.PLUGIN.slug: bandhan.PLUGIN,
    dcb.PLUGIN.slug: dcb.PLUGIN,
}
